### ISSUE TITLE
Error with --dev=true

### ISSUE THREAD

**Issue by stevoland** [facebookarchive/react-page#13]
node server.js --dev=true

```
Bundling 105 JS files for /index.html   -   HTML blocks UI, JS Gen does not
----------------------------------------------------------------------------------------------------------------------------------------------------
HTML Gen: find/transform 618ms (WARMING UP ON FIRST LOAD)                                                  c render 223ms                       se

Error: ERROR RENDERING PAGE ON SERVER:
<mapped error>
ReferenceError: window is not defined
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-tools/src/test/ReactDefaultPerf.js:409:21
    at require (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/polyfill/require.js:232:25)
    at Object.inject (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-tools/src/core/ReactDefaultInjection.js:71:39)
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-tools/src/core/React.js:32:23
    at require (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/polyfill/require.js:232:25)
    at /Volumes/Data/Users/stevo/git/react-page/src/elements/VectorWidget/VectorWidget.js:143:16
    at Object.Contextify.sandbox.run (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/node_modules/contextify/lib/contextify.js:12:24)
    at renderReactPage (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/renderReactPage.js:77:13)
    at renderedBundledText (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/index.js:165:5)
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/guard.js:29:10
</mapped error>

    at renderReactPage (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/renderReactPage.js:99:18)
    at renderedBundledText (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/index.js:165:5)
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/guard.js:29:10
    at Packager.computePackageForAbsolutePath.merge.onComputePackageDone (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/index.js:140:7)
    at Object.onComputePackageDone (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/guard.js:29:10)
    at onWarmed (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/Packager.js:259:17)
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/node_modules/async/lib/async.js:116:25
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/node_modules/async/lib/async.js:24:16
    at warmCache (/Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/src/Packager.js:222:5)
    at /Volumes/Data/Users/stevo/git/react-page/node_modules/react-page-middleware/node_modules/async/lib/async.js:108:13
```

**Comment by petehunt** [comment]
Our bad, fixing this now

**Comment by vjeux** [comment]
@petehunt did you fix it?

**Comment by petehunt** [comment]
Yep
