### ISSUE TITLE
Error in Windows 7 

### ISSUE THREAD

**Issue by ciromaciel** [facebookarchive/react-page#25]
When requesting a page http://localhost:8080/index.html get the following error:

I am running on Windows 7

Connect
500 Error: No modules for:C:\Users\lilo003\Downloads\react-page-master\src\index.js
at onWarmed (C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\src\Packager.js:267:13)
at Object.async.each (C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\node_modules\async\lib\async.js:104:20)
at Object.onModuleDependenciesLoaded [as done](C:Userslilo003Downloadsreact-page-masternode_modulesreact-page-middlewaresrcPackager.js:270:13)
at MapUpdateTask. (C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\node_modules\node-haste\lib\HasteDependencyLoader.js:103:13)
at MapUpdateTask.EventEmitter.emit (events.js:117:20)
at MapUpdateTask. (C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:80:18)
at finished (C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:267:16)
at C:\Users\lilo003\Downloads\react-page-master\node_modules\react-page-middleware\node_modules\node-haste\lib\loader\ResourceLoader.js:145:5
at process._tickCallback (node.js:415:13)
## 

Ciro

**Comment by jordwalke** [comment]
Thank you for reporting this.

**Comment by efdee** [comment]
+1

**Comment by jordwalke** [comment]
The page has been updated to indicate that Mac OS and Linux are supported. If anyone were to send a PR to fix the bugs in windows, I would be extremely grateful! (They are in node-haste).
