### ISSUE TITLE
500: No modules for C:\[...]\react-page\app\index.js

### ISSUE THREAD

**Issue by OClement** [facebookarchive/react-page#33]
everything is up to date, latest version
Did npm install and what not

When trying to run the server and accessing index.html I get this error:

Error: No modules for:C:[...]\react-page\app\index.js
    at onWarmed (C:[...]\react-page\node_modules\react-page-middleware\src\Packager.js:267:13)
    at Object.async.each (C:[...]\react-page\node_modules\react-page-middleware\node_modules\async\lib\async.js:104:20)
    at Object.onModuleDependenciesLoaded [as done](C:[...]react-pagenode_modulesreact-page-middlewaresrcPackager.js:270:13)
    at MapUpdateTask.<anonymous> (C:[...]\react-page\node_modules\react-page-middleware\node_modules\node-haste\lib\HasteDependencyLoader.js:103:13)
    at MapUpdateTask.EventEmitter.emit (events.js:117:20)
    at MapUpdateTask.<anonymous> (C:[...]\react-page\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:80:18)
    at finished (C:[...]\react-page\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:267:16)
    at C:[...]\react-page\node_modules\react-page-middleware\node_modules\node-haste\lib\loader\ResourceLoader.js:145:5
    at process._tickCallback (node.js:415:13)

**Comment by montlebalm** [comment]
I'm getting something similar. Downloaded zip from Github, npm install, node server.js:

```
500 Error: No modules for:[...]\src\index.js
at onWarmed ([...]\node_modules\react-page-middleware\src\Packager.js:267:13)
at Object.async.each ([...]\node_modules\react-page-middleware\node_modules\async\lib\async.js:104:20)
at Object.onModuleDependenciesLoaded [as done] ([...]\node_modules\react-page-middleware\src\Packager.js:270:13)
at MapUpdateTask. ([...]\node_modules\react-page-middleware\node_modules\node-haste\lib\HasteDependencyLoader.js:103:13)
at MapUpdateTask.EventEmitter.emit (events.js:117:20)
at MapUpdateTask. ([...]\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:80:18)
at finished ([...]\node_modules\react-page-middleware\node_modules\node-haste\lib\MapUpdateTask.js:267:16)
at [...]\node_modules\react-page-middleware\node_modules\node-haste\lib\loader\ResourceLoader.js:145:5
at process._tickCallback (node.js:415:13)
```

**Comment by jordwalke** [comment]
We still have some work to do with one of `react-page`'s dependencies (`node-haste`) on windows to get `react-page` working. I'll update the project description to be clear about this, and if you are able to make a pull request to fix any issues, we'd definitely appreciate it. Check out the `node-haste` issue here, to follow along with the progress. It's probably something very simple to fix once we track down the issue:

https://github.com/facebook/node-haste/pull/2
