### ISSUE TITLE
Cannot set property 'mtime' of null

### ISSUE THREAD

**Issue by gpbl** [facebookarchive/react-page#46]
Hello, 
I'm evaluating React as a view replacement, trying to see how it works for server-side rendering.

My project is using the following developer dependencies:

``` json
{"devDependencies": {
    "bower": "~1.2.8",
    "grunt": "~0.4.2",
    "grunt-bower-requirejs": "~0.8.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-compass": "~0.7.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.7.0",
    "grunt-contrib-htmlmin": "~0.1.3",
    "grunt-contrib-jasmine": "~0.5.2",
    "grunt-contrib-jshint": "~0.8.0",
    "grunt-contrib-uglify": "~0.2.7",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-nginx": "~0.2.1",
    "grunt-open": "~0.2.2",
    "grunt-react": "~0.6.0",
    "grunt-requirejs": "~0.4.0",
    "grunt-rev": "~0.1.0",
    "grunt-usemin": "~2.0.2",
    "jshint-stylish": "~0.1.4",
    "load-grunt-tasks": "~0.2.1",
    "time-grunt": "~0.2.5"
  }
}
```

...just add them to the react-page's package.json, run `npm install` and then `node server`.

Now when I visit [localhost:8080/index.html](http://localhost:8080/index.html), I get the error _Cannot set property 'mtime' of null_. 

```
/react-page/node_modules/react-page-middleware/node_modules/node-haste/lib/MapUpdateTask.js:179
          resource.mtime = record.mtime;
                         ^
TypeError: Cannot set property 'mtime' of null
    at ~/Development/react-page/node_modules/react-page-middleware/node_modules/node-haste/lib/MapUpdateTask.js:179:26
    at ~/Development/react-page/node_modules/react-page-middleware/node_modules/node-haste/lib/loader/ResourceLoader.js:88:7
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```

After diving a bit into react-page-middleware/node-haste code I'm asking here for help since I can't find the cause of the problem. 

For curiosity, why is node-haste looking into node_modules? The first-page load is also much slower when adding other modules. It would be nice to have a more in-depth documentation on how the middleware works.

Thank you!

**Comment by jordwalke** [comment]
The first page load is slow because it reindexes new dependencies and caches them. The following load is much faster as it uses the cache. As mentioned on `react-page-middleware`, for large scale deployments you'll want to build your own server side rendering integration into your stack, but react-page/middleware is a good example to get you started.

The reason why it looks in `node_modules`, is because your client side code can require anything you've `npm install`ed and it will get bundled up with source maps into your browser. You should provide a blacklist regular expression to `node server.js --blacklistRE=` to prevent it from looking into the dev dependencies to make it _much_ faster. That might help the failure you're seeing, but it really shouldn't be failing at all. Just to confirm, you're on Linux or OS X?

**Comment by rboyce** [comment]
I haven't spent any time investigating, but I encountered the same issue and deleting my `node_modules` directory and re-running `npm install` fixed the problem.

**Comment by gpbl** [comment]
Thank you for the clarifications, now I understand better. I don't see a big limit excluding dev modules from the client - but still it's an issue with some dependencies. I'm on OS X. 

I'm indeed looking for a server side rendering solution. The starting points I've found are good to show that _it works_, but I miss some explanations about the concepts behind. While writing my own implementation, I feel other people have gone through the same problems... I'll better write to the google group for this. Can't wait to work with React!

**Comment by jordwalke** [comment]
@bugbot: That makes sense. React is performing rendering of UI on the server in a way that is completely new. We only recently discovered that this was possible TBPH. You're absolutely correct that we're all going to find the same types of challenges. For example, someone posted a very thoughtful question about data fetching at the component level:

http://stackoverflow.com/questions/20815423/how-to-render-asynchronously-initialized-components-on-the-server

 `react-page` is a project where we can fork, discuss and share what works/what doesn't.

The bug you're finding is completely unrelated and we just have to fix it. Do you know which of the modules is problematic?

**Comment by gpbl** [comment]
@jordwalke I couldn't find the problematic one: it seems to happen after adding a certain amount of modules. It is more related to the node-haste project. Anyway, let see how far I can go: community contributions are indeed very inspirational!

**Comment by jordwalke** [comment]
Would you try adding all the dev dependencies to the `blacklistRE` regular expression?

Pass this parameter to the `server.js` script:

`--blacklistRE='(node_modules/some_module/|node_modules/some_other_module)'`

Note how the modules are separated by `|`.

Since they are only dev dependencies, they should not be needed for your actual app, and so `react-page` wouldn't need to look at them at all.

**Comment by gpbl** [comment]
It seems to be the grunt module: when running `node server --blacklistRE='(node_modules/grunt)'`, it works.

**Comment by jaredwy** [comment]
It is not ideal, but i made a quick work around in server.js 

var pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, "./package.json")));
var defaultBlackList = "(" +Object.keys(pkg.devDependencies).join("|") + ")";

I then just load this regex and allow an override from the command line if you need. It is less than ideal, but since react-page seems to be a dead project  it will do :D 
Just hoping to give another solution to anyone else who hits this issue.
