### ISSUE TITLE
Syntax error crashes node server

### ISSUE THREAD

**Issue by petehunt** [facebookarchive/react-page#6]
Open http://localhost:8080/index.html

/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/vendor/fbtransform/lib/transform.js:99
    throw e;
          ^
Error: Parse Error: Line 418: Unexpected token )
    at throwError (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:2132:21)
    at throwUnexpected (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:2194:9)
    at parseVariableIdentifier (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:3251:13)
    at /Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:5717:38
    at parseObjectProperty (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:2448:27)
    at /Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:5717:38
    at parseObjectInitialiser (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:2492:24)
    at parsePrimaryExpression (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:2635:20)
    at /Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:5717:38
    at trackLeftHandSideExpressionAllowCall (/Users/phunt/Projects/preparable-react/node_modules/react-page-middleware/node_modules/react-tools/node_modules/esprima/esprima.js:5617:61)

Server then promptly dies and I'm back in bash.

**Comment by jordwalke** [comment]
That's like - the _opposite_ of what we want to do!

**Comment by jordwalke** [comment]
This should be fixed now if you reclone and `npm install` again.

**Comment by jordwalke** [comment]
Fixed!
